### ISSUE TITLE
Segmentation fault with Carabiner and Bitwig on Debian 10

### ISSUE THREAD

**Issue by ovitus** [Deep-Symmetry/carabiner#20] opened 2021-03-18 20:17 UTC
I get the following error in syslog after a few seconds having Carabiner and Bitwig synchronized. The Peers value flicks beteween 0 and 1 and then it segfaults:

Mar 18 16:08:46 ovitus kernel: Carabiner_Linux[4654]: segfault at 0 ip 000055608e00d696 sp 00007f9df5ddb410 error 4 cpu 12 in Carabiner_Linux_x64[55608de00000+2d7000]
Mar 18 16:08:46 ovitus kernel: Code: 95 c0 c9 c3 55 48 89 e5 48 83 ec 10 48 89 7d f8 48 8b 45 f8 48 89 c7 e8 dc 34 00 00 c9 c3 55 48 89 e5 48 89 7d f8 48 8b 45 f8 <48> 8b 00 5d c3 90 55 48 89 e5 48 89 7d f8 48 8b 45 f8 48 83 c0 08

**Comment by brunchboy** [comment] 2021-03-18 20:18
I don’t have Bitwig or much access to Linux these days, so if you can figure this out a PR would be much appreciated!

**Comment by brunchboy** [comment] 2021-03-18 20:20
Also, since 99.9% of Carabiner is Ableton Link, I would encourage you to see if you can reproduce this with LinkHut or other Link testing tools from that project, and if so, open the issue against the Link project itself. https://github.com/Ableton/link

**Comment by ovitus** [comment] 2021-03-18 23:42
I compared a laptop that had the same OS and installation without any issue and the laptop had firewalld installed, so I installed it on this PC.. That solved the problem, no more crashing. (:

**Comment by brunchboy** [comment] 2021-03-19 03:14
That’s strange! I still think that if you can reproduce this with just the Link test tools (like LinkHut) then Ableton will want to know about it and fix it.

**Comment by brunchboy** [comment] 2021-04-21 03:11
If there is no new information about this, I will close the issue soon.

**Closed as completed** 2022-02-20 04:11 UTC
Labels: help wanted
