### ISSUE TITLE
can't compile on windows.

### ISSUE THREAD

**Issue by nonspacial** [Deep-Symmetry/carabiner#4] opened 2017-12-27 13:18 UTC
Hi, following your instructions i can only get 7% compiliation in Powershell using MinGW and/or MSYS.

If i get a stable release of gflags i get 12%. I began a thread @ stackoverflow here:

[https://stackoverflow.com/questions/47835484/trying-to-compile-carabiner-on-windows-using-powershell-and-mingw-msys-having-a/47839302#_=_](url)

There are screenshots there in the original question.

Please help.

Thanks Robbie

**Comment by brunchboy** [comment] 2017-12-30 23:01
Unfortunately I don’t use Windows, and so can’t offer help in this. Your StackOverflow [question](https://stackoverflow.com/questions/47835484/trying-to-compile-carabiner-on-windows-using-powershell-and-mingw-msys-having-a/47839302#=) was the right approach, it is a pity that nobody there is helping.

**Comment by sergioherculano** [comment] 2018-04-26 13:52
Hi,
I just compiled Carabiner in Windows x64 if someone wants I can provide the .exe file

**Comment by shanbady** [comment] 2018-04-26 17:47
@sergioherculano I would love to get the exe. what was the trick to getting it to compile?

**Comment by brunchboy** [comment] 2018-04-26 19:21
Yes, I’d love to correct the project or add instructions so that it builds properly for everyone, is that straightforward?

**Comment by sergioherculano** [comment] 2018-04-26 23:37
Was a entire night strugling with some missing files and them configure the correct path of cl compiler, then finale it compiler and I was able to run but unfortunatelly I own a DDJ-RZX and since carabiner and beat-link-trigger works only with Pro DJ Link I am not able to use it :( 

I am sending it attached for the colleagues test it 

Enjoy

[carabiner-master-win-x64.zip](https://github.com/brunchboy/carabiner/files/1953344/carabiner-master-win-x64.zip)

**Comment by kris-audio** [comment] 2018-04-27 12:49
You have to be joking haha, I bought a Macbook so i could use carabiner. Well I goofed, ill get back to you about testing the exe file, ill do that later :)

**Comment by brunchboy** [comment] 2018-04-29 17:23
Thanks, Sergio, can you reproducibly build it now? Are there any changes needed to this project or the instructions so that it can build on both Mac and Windows? I’d very much appreciate receiving those either as instructions for me or as a Pull Request.

**Comment by shanbady** [comment] 2018-04-30 00:02
here are steps that I was able to use to get it to compile to windows - luckily no project changes necessary. 

1 - download and install cmake for windows.
2 - download and install Visual Studio 2017
3 - using the cmake gui program set this project as the source directory and set the makefile generator to "Visual Studio 2015"
![capture](https://user-images.githubusercontent.com/196425/39412303-2b56b01e-4be8-11e8-95e7-f4d9b92dbdf8.PNG)

4 - click "configure" then "generate" - at the end of this process it will ask if you want to open the project files in Visual Studio (click yes).
5 - build the project in visual studio which should successfully compile an exe.

**Comment by brunchboy** [comment] 2018-04-30 02:42
Thanks for sharing those instructions! Hopefully they will be helpful to people who want to make their own builds.

**Comment by brunchboy** [comment] 2018-04-30 04:00
Thanks, I finally bit the bullet and downloaded Visual Studio 2017 Community Edition inside a VMware Fusion Windows 10 virtual machine myself, and was able to follow these directions and build Carabiner.exe. I will place that on the downloads page for others.

**Comment by brunchboy** [comment] 2018-04-30 04:05
If someone could test my new Carabiner_win_x64.zip download on the [Releases](https://github.com/brunchboy/carabiner/releases) page, and let me know if it works on a real, live Windows system, we might be able to finally close this issue! Thanks, everyone! 😄

**Comment by brunchboy** [comment] 2018-05-24 16:32
Having not heard anything from anyone, I am going to assume that it works, since it does work in my Windows VM.

**Closed as completed by brunchboy** 2018-05-24 16:32 UTC
Labels: help wanted

**Comment by brunchboy** [comment] 2020-01-14 00:59
I also figured out how to do this entirely from the command line, and am now automatically building and releasing both the Windows and MacOS executables using GitHub Actions whenever a change is pushed to this repository. Here is the [relevant part of the workflow](https://github.com/Deep-Symmetry/carabiner/blob/master/.github/workflows/build.yml#L27-L31), in case anyone wants to do it by hand, but if you fork the project, you will get automatic builds in the cloud as well.
